/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    widgets: Widget;
    amenities: Amenity;
    'project-types': ProjectType;
    'project-statuses': ProjectStatus;
    'bhk-types': BhkType;
    testimonials: Testimonial;
    projects: Project;
    'blog-categories': BlogCategory;
    posts: Post;
    policies: Policy;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    widgets: WidgetsSelect<false> | WidgetsSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    'project-types': ProjectTypesSelect<false> | ProjectTypesSelect<true>;
    'project-statuses': ProjectStatusesSelect<false> | ProjectStatusesSelect<true>;
    'bhk-types': BhkTypesSelect<false> | BhkTypesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'impact-page': ImpactPage;
    'about-page': AboutPage;
    'home-page': HomePage;
    'contact-page': ContactPage;
    'blog-page': BlogPage;
  };
  globalsSelect: {
    'impact-page': ImpactPageSelect<false> | ImpactPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "widgets".
 */
export interface Widget {
  id: number;
  title: string;
  type: 'media-gallery' | 'testimonial-carousel' | 'project-showcase' | 'custom';
  description?: string | null;
  media?: (number | Media)[] | null;
  testimonials?: (number | Testimonial)[] | null;
  projects?: (number | Project)[] | null;
  /**
   * Custom JSON data for widget
   */
  customData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  location: string;
  /**
   * Testimonial type
   */
  type: 'text' | 'video';
  textContent?: string | null;
  rating?: number | null;
  /**
   * Choose video source
   */
  videoSource?: ('upload' | 'youtube' | 'vimeo') | null;
  video?: (number | null) | Media;
  /**
   * Poster/cover image for video
   */
  poster?: (number | null) | Media;
  youtubeUrl?: string | null;
  vimeoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  location?: string | null;
  status?: (number | null) | ProjectStatus;
  projectType?: (number | null) | ProjectType;
  slug?: string | null;
  coverImage?: (number | null) | Media;
  detailCoverImage?: (number | null) | Media;
  contentImage?: (number | null) | Media;
  reraNo?: string | null;
  projectArea?: string | null;
  priceRangeStartFrom?: number | null;
  bhkTypes?: (number | BhkType)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  amenities?: (number | Amenity)[] | null;
  locationAddress?: string | null;
  locationMapUrl?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  keyTransports?:
    | {
        type?: string | null;
        name?: string | null;
        distance?: string | null;
        id?: string | null;
      }[]
    | null;
  videoUrl?: string | null;
  images?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  floorPlans?:
    | {
        plan?: (number | null) | Media;
        label?: string | null;
        rooms?: number | null;
        bathrooms?: number | null;
        size?: string | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        video?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaKeywords?: string | null;
  canonicalUrl?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  /**
   * Recommended size: 1200×630px. Defaults to Cover Image if left blank.
   */
  ogImage?: (number | null) | Media;
  twitterCard?: ('summary' | 'summary_large_image') | null;
  twitterTitle?: string | null;
  twitterDescription?: string | null;
  /**
   * Paste raw JSON-LD here for RealEstateListing or custom schema. This will be injected into <script type="application/ld+json"> on the page.
   */
  structuredData?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-statuses".
 */
export interface ProjectStatus {
  id: number;
  name: string;
  /**
   * Stable key used in URLs and filters. The "completed" status drives the Completed Projects page. Auto-generated from name if left blank.
   */
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-types".
 */
export interface ProjectType {
  id: number;
  name: string;
  /**
   * Stable key used in URLs and filters. Auto-generated from name if left blank.
   */
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bhk-types".
 */
export interface BhkType {
  id: number;
  name: string;
  /**
   * Stable key used in URLs and filters. Auto-generated from name if left blank.
   */
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  name: string;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: string | null;
  categories?: (number | BlogCategory)[] | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaKeywords?: string | null;
  canonicalUrl?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  /**
   * Recommended size: 1200×630px. Defaults to Cover Image if left blank.
   */
  ogImage?: (number | null) | Media;
  twitterCard?: ('summary' | 'summary_large_image') | null;
  twitterTitle?: string | null;
  twitterDescription?: string | null;
  /**
   * Paste raw JSON-LD here for Article or BreadcrumbList schema. This will be injected into <script type="application/ld+json"> on the page.
   */
  structuredData?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number;
  title: string;
  /**
   * Used in the page URL — use lowercase with hyphens
   */
  slug: string;
  /**
   * Date displayed to users as "Last Updated" on the policy page
   */
  lastUpdated?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Form submissions from Contact & Project Enquiry forms
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  formType?: ('contact' | 'enquiry' | 'newsletter') | null;
  name: string;
  /**
   * Required for contact/enquiry, optional for newsletter
   */
  phone?: string | null;
  whatsappActivated?: boolean | null;
  email: string;
  budget?: string | null;
  message?: string | null;
  project?: string | null;
  isSpam?: boolean | null;
  /**
   * Success/fail of each pipeline step for this submission
   */
  delivery?: {
    sheetsStored?: boolean | null;
    sheetsError?: string | null;
    adminEmailSent?: boolean | null;
    userEmailSent?: boolean | null;
    emailError?: string | null;
  };
  tracking?: {
    ip?: string | null;
    /**
     * Browser user agent string
     */
    userAgent?: string | null;
    /**
     * Immediate HTTP Referer header from form submission
     */
    referrer?: string | null;
    /**
     * Hostname extracted from first-touch referrer
     */
    referrerDomain?: string | null;
    /**
     * Page path before form submit
     */
    previousPage?: string | null;
    /**
     * User's last 20 page visits in this session
     */
    pageHistory?: string | null;
  };
  firstTouch?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    gclId?: string | null;
    fbClId?: string | null;
    landingPage?: string | null;
    timestamp?: string | null;
  };
  lastTouch?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    gclId?: string | null;
    fbClId?: string | null;
    currentPage?: string | null;
    timestamp?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'widgets';
        value: number | Widget;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'project-types';
        value: number | ProjectType;
      } | null)
    | ({
        relationTo: 'project-statuses';
        value: number | ProjectStatus;
      } | null)
    | ({
        relationTo: 'bhk-types';
        value: number | BhkType;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'policies';
        value: number | Policy;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "widgets_select".
 */
export interface WidgetsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  description?: T;
  media?: T;
  testimonials?: T;
  projects?: T;
  customData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-types_select".
 */
export interface ProjectTypesSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-statuses_select".
 */
export interface ProjectStatusesSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bhk-types_select".
 */
export interface BhkTypesSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  type?: T;
  textContent?: T;
  rating?: T;
  videoSource?: T;
  video?: T;
  poster?: T;
  youtubeUrl?: T;
  vimeoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  status?: T;
  projectType?: T;
  slug?: T;
  coverImage?: T;
  detailCoverImage?: T;
  contentImage?: T;
  reraNo?: T;
  projectArea?: T;
  priceRangeStartFrom?: T;
  bhkTypes?: T;
  description?: T;
  amenities?: T;
  locationAddress?: T;
  locationMapUrl?: T;
  latitude?: T;
  longitude?: T;
  keyTransports?:
    | T
    | {
        type?: T;
        name?: T;
        distance?: T;
        id?: T;
      };
  videoUrl?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  floorPlans?:
    | T
    | {
        plan?: T;
        label?: T;
        rooms?: T;
        bathrooms?: T;
        size?: T;
        price?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        video?: T;
        caption?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  canonicalUrl?: T;
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  twitterCard?: T;
  twitterTitle?: T;
  twitterDescription?: T;
  structuredData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  author?: T;
  categories?: T;
  status?: T;
  publishedAt?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  canonicalUrl?: T;
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  twitterCard?: T;
  twitterTitle?: T;
  twitterDescription?: T;
  structuredData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lastUpdated?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  phone?: T;
  whatsappActivated?: T;
  email?: T;
  budget?: T;
  message?: T;
  project?: T;
  isSpam?: T;
  delivery?:
    | T
    | {
        sheetsStored?: T;
        sheetsError?: T;
        adminEmailSent?: T;
        userEmailSent?: T;
        emailError?: T;
      };
  tracking?:
    | T
    | {
        ip?: T;
        userAgent?: T;
        referrer?: T;
        referrerDomain?: T;
        previousPage?: T;
        pageHistory?: T;
      };
  firstTouch?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        gclId?: T;
        fbClId?: T;
        landingPage?: T;
        timestamp?: T;
      };
  lastTouch?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        gclId?: T;
        fbClId?: T;
        currentPage?: T;
        timestamp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-page".
 */
export interface ImpactPage {
  id: number;
  heroImage?: (number | null) | Media;
  environmentalSection: {
    /**
     * Short label shown above the heading (e.g. OUR ENVIRONMENTAL IMPACT)
     */
    label?: string | null;
    heading: string;
    description: string;
    image?: (number | null) | Media;
  };
  socialSection: {
    /**
     * Short label shown above the heading (e.g. OUR SOCIAL IMPACT)
     */
    label?: string | null;
    heading: string;
    description: string;
    image?: (number | null) | Media;
  };
  /**
   * Quotes shown in the carousel at the bottom of the page
   */
  testimonials?:
    | {
        quote: string;
        name: string;
        company?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Recommended size: 1200×630px
     */
    ogImage?: (number | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroBanner: {
    /**
     * Gold-coloured heading shown on the green hero banner
     */
    tagline: string;
    /**
     * White body text shown below the tagline
     */
    description: string;
  };
  heroQuote: {
    /**
     * Large centred quote displayed over the background image
     */
    quote: string;
    backgroundImage?: (number | null) | Media;
  };
  /**
   * Key numbers shown in the stats row (e.g. 20+ Completed Projects)
   */
  stats?:
    | {
        number: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  valuesSection?: {
    /**
     * Heading shown on the left of the dark brown panel (e.g. Our Values)
     */
    sectionHeading?: string | null;
    sectionImage?: (number | null) | Media;
    /**
     * Mission, Vision, and any additional value items
     */
    values?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  founderStory?: {
    heading?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    photo?: (number | null) | Media;
  };
  testimonialsSectionHeading?: string | null;
  /**
   * Pick testimonials to feature in the carousel
   */
  featuredTestimonials?: (number | Testimonial)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Recommended size: 1200×630px
     */
    ogImage?: (number | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    heroImage?: (number | null) | Media;
  };
  latestProjectsSection: {
    /**
     * Small label shown above the heading (e.g. LATEST PROJECTS)
     */
    sectionLabel?: string | null;
    heading: string;
    buttonLabel?: string | null;
    /**
     * Projects shown in the home page carousel
     */
    featuredProjects?: (number | Project)[] | null;
  };
  whoWeAreSection: {
    /**
     * Small label shown above the heading (e.g. WHO WE ARE)
     */
    sectionLabel?: string | null;
    /**
     * Large centred heading shown on the green background section
     */
    heading: string;
    /**
     * Exactly 3 cards — e.g. What we do, Our Impact, Core Values
     */
    featureCards?:
      | {
          title: string;
          description: string;
          buttonLabel: string;
          backgroundImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Counter stats shown below the feature cards (e.g. 20+ Completed Projects)
     */
    stats?:
      | {
          number: string;
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  ongoingProjectsSection?: {
    heading?: string | null;
    /**
     * Projects listed on the left of the map and pinned on the map
     */
    projects?: (number | Project)[] | null;
  };
  commitmentSection: {
    /**
     * Small label shown above the heading (e.g. OUR COMMITMENT)
     */
    sectionLabel?: string | null;
    heading: string;
    description: string;
    /**
     * Large building photo shown behind the commitment cards
     */
    backgroundImage?: (number | null) | Media;
    /**
     * 3 cards — e.g. Corporate Responsibility, Experts with Team Spirit, Security & Compliance
     */
    commitments?:
      | {
          /**
           * Icon shown in the green circle (SVG or PNG, 30×30)
           */
          icon?: (number | null) | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  howWeBuildSection: {
    /**
     * Small label shown above the heading
     */
    sectionLabel?: string | null;
    heading: string;
    description?: string | null;
    /**
     * Steps shown in the process timeline (e.g. Planning, Design, Construction, Delivery)
     */
    steps?:
      | {
          stepNumber: number;
          title: string;
          description: string;
          /**
           * Icon for this step (SVG or PNG)
           */
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  completedProjectsSection: {
    /**
     * Small label shown above the heading (e.g. COMPLETED PROJECTS)
     */
    sectionLabel?: string | null;
    heading: string;
    description?: string | null;
    buttonLabel?: string | null;
    /**
     * Projects shown in the completed projects grid (typically 3)
     */
    featuredProjects?: (number | Project)[] | null;
  };
  testimonialsSectionHeading?: string | null;
  /**
   * Mix of text and video testimonials to show in the home page carousel
   */
  featuredTestimonials?: (number | Testimonial)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Recommended size: 1200×630px
     */
    ogImage?: (number | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  /**
   * Building/property photo shown as the hero background (desktop)
   */
  heroImage?: (number | null) | Media;
  /**
   * Mobile-optimized hero background image (optional, falls back to heroImage if not set)
   */
  mobileHeroImage?: (number | null) | Media;
  contactDetails: {
    /**
     * Full mailing address displayed on the contact page
     */
    address: string;
    email: string;
    /**
     * Primary phone number
     */
    phone: string;
    /**
     * WhatsApp number (if different from the primary phone)
     */
    whatsapp?: string | null;
  };
  contactForm?: {
    /**
     * Heading shown above the enquiry form
     */
    heading?: string | null;
    /**
     * Small text shown below the Message field
     */
    disclaimer?: string | null;
    /**
     * Message shown after form submission
     */
    successMessage?: {
      /**
       * Heading text (e.g., "Thank you!", "Success!")
       */
      heading?: string | null;
      /**
       * Body text of the success message
       */
      message?: string | null;
      /**
       * Optional link shown in the success message
       */
      link?: {
        /**
         * Text displayed for the link
         */
        text?: string | null;
        /**
         * URL the link points to
         */
        url?: string | null;
      };
    };
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Recommended size: 1200×630px
     */
    ogImage?: (number | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  /**
   * Hero banner image shown on blog listing page (desktop)
   */
  heroImage?: (number | null) | Media;
  /**
   * Mobile-optimized hero banner image (optional, falls back to heroImage if not set)
   */
  mobileHeroImage?: (number | null) | Media;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Recommended size: 1200×630px
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-page_select".
 */
export interface ImpactPageSelect<T extends boolean = true> {
  heroImage?: T;
  environmentalSection?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        image?: T;
      };
  socialSection?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        image?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        company?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroBanner?:
    | T
    | {
        tagline?: T;
        description?: T;
      };
  heroQuote?:
    | T
    | {
        quote?: T;
        backgroundImage?: T;
      };
  stats?:
    | T
    | {
        number?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  valuesSection?:
    | T
    | {
        sectionHeading?: T;
        sectionImage?: T;
        values?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  founderStory?:
    | T
    | {
        heading?: T;
        content?: T;
        photo?: T;
      };
  testimonialsSectionHeading?: T;
  featuredTestimonials?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroImage?: T;
      };
  latestProjectsSection?:
    | T
    | {
        sectionLabel?: T;
        heading?: T;
        buttonLabel?: T;
        featuredProjects?: T;
      };
  whoWeAreSection?:
    | T
    | {
        sectionLabel?: T;
        heading?: T;
        featureCards?:
          | T
          | {
              title?: T;
              description?: T;
              buttonLabel?: T;
              backgroundImage?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              number?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
      };
  ongoingProjectsSection?:
    | T
    | {
        heading?: T;
        projects?: T;
      };
  commitmentSection?:
    | T
    | {
        sectionLabel?: T;
        heading?: T;
        description?: T;
        backgroundImage?: T;
        commitments?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  howWeBuildSection?:
    | T
    | {
        sectionLabel?: T;
        heading?: T;
        description?: T;
        steps?:
          | T
          | {
              stepNumber?: T;
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  completedProjectsSection?:
    | T
    | {
        sectionLabel?: T;
        heading?: T;
        description?: T;
        buttonLabel?: T;
        featuredProjects?: T;
      };
  testimonialsSectionHeading?: T;
  featuredTestimonials?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroImage?: T;
  mobileHeroImage?: T;
  contactDetails?:
    | T
    | {
        address?: T;
        email?: T;
        phone?: T;
        whatsapp?: T;
      };
  contactForm?:
    | T
    | {
        heading?: T;
        disclaimer?: T;
        successMessage?:
          | T
          | {
              heading?: T;
              message?: T;
              link?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  heroImage?: T;
  mobileHeroImage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}