// Specific WordPress URL redirects
// Map old WordPress slugs to new Next.js URLs
// Users can add specific mappings here

export const wordpressSpecificRedirects = [
  // Blog posts (old flat URLs → /blog/:slug)
  { source: '/blog-visvas-promoters-madurai', destination: '/blog', permanent: true },
  { source: '/credai-fairpro-2026-madurai', destination: '/blog/credai-fairpro-2026-madurai', permanent: true },
  { source: '/investments-and-diversification-at-visvas', destination: '/blog/investments-and-diversification-at-visvas', permanent: true },
  { source: '/visvas-promoters-most-trusted-builders-in-madurai', destination: '/blog/visvas-promoters-most-trusted-builders-in-madurai', permanent: true },
  { source: '/top-residential-project-in-madurai-new-projects-for-sale', destination: '/blog/top-residential-project-in-madurai-new-projects-for-sale', permanent: true },
  { source: '/independent-villa-for-sale-in-madurai', destination: '/blog/independent-villa-for-sale-in-madurai', permanent: true },
  { source: '/flats-in-madurai', destination: '/blog/flats-in-madurai', permanent: true },
  { source: '/residential-and-commercial-land-plots-for-sale-in-madurai', destination: '/blog/residential-and-commercial-land-plots-for-sale-in-madurai', permanent: true },
  { source: '/visvas-promoters-properties-for-sale-in-madurai', destination: '/blog/visvas-promoters-properties-for-sale-in-madurai', permanent: true },
  { source: '/rera-major-benefits-of-new-rera-act-for-home-buyers', destination: '/blog/rera-major-benefits-of-new-rera-act-for-home-buyers', permanent: true },
  { source: '/visvas-agrini-enclave', destination: '/blog/visvas-agrini-enclave', permanent: true },
  { source: '/gated-community-independent-villa-for-sale-in-madurai', destination: '/blog/gated-community-independent-villa-for-sale-in-madurai', permanent: true },
  { source: '/gated-communities-in-madurai', destination: '/blog/gated-communities-in-madurai', permanent: true },
  { source: '/ultimate-guide-to-buying-a-house', destination: '/blog/ultimate-guide-to-buying-a-house', permanent: true },
  { source: '/buying-an-apartment-flats-for-sale-in-madurai', destination: '/blog/buying-an-apartment-flats-for-sale-in-madurai', permanent: true },

  // Projects (old /projects/:old-slug → /projects/:new-slug)
  { source: '/projects', destination: '/projects/ongoing', permanent: true },
  { source: '/projects/madhyapuri-3-bhk-apartments-for-sale-in-madurai', destination: '/projects/madhyapuri', permanent: true },
  { source: '/projects/ajita-thuvarimaan', destination: '/projects/ajita', permanent: true },
  { source: '/projects/vaaruni-enclave', destination: '/projects/vaaruni-enclave', permanent: true },
  { source: '/projects/vidhatri-ponmeni', destination: '/projects/vidhatri', permanent: true },
  { source: '/projects/aparna-1-bhk-apartment-thuvarimaan-madurai', destination: '/projects/aparna---1bhk', permanent: true },
  { source: '/projects/aparna-2-bhk-apartments-for-sale-in-madurai', destination: '/projects/aparna---2bhk', permanent: true },
  { source: '/projects/aparna-studio-apartments-for-sale-in-madurai', destination: '/projects/aparna---1bhk', permanent: true },
  { source: '/projects/virat-2bhk-apartments-vilangudi-madurai', destination: '/projects/virat', permanent: true },
  { source: '/projects/virat-3bhk-apartments-vilangudi-madurai', destination: '/projects/virat', permanent: true },
  { source: '/projects/supraja-ready-for-possession', destination: '/projects/supraja', permanent: true },
  { source: '/projects/supraja-villa-1-5-bhk', destination: '/projects/supraja', permanent: true },
  { source: '/projects/vibhava-h-block-apartments-for-sale-in-ponmeni', destination: '/projects/vibhava', permanent: true },
  { source: '/projects/ajita-premium-3-bhk-villa-for-sale-in-madurai', destination: '/projects/ajita-phase-ii', permanent: true },
  { source: '/projects/ajita-premium-4-bhk-villa-for-sale-in-madurai', destination: '/projects/ajita-phase-i-extension---b-block', permanent: true },
  { source: '/projects/agrini-enclave-ready-to-move', destination: '/projects/agrini', permanent: true },
  { source: '/projects/vajra-ready-to-live-apartments-madurai', destination: '/projects/vajra', permanent: true },
  { source: '/projects/aprameya-2-bhk-villa-for-sale-in-madurai', destination: '/projects/aprameya', permanent: true },
  { source: '/projects/visvas-vasudhara-ready-to-move-villas-and-flats', destination: '/projects/vasudhara', permanent: true },

  // Static/legal/portal pages
  { source: '/contact-1-best-property-developer-in-madurai', destination: '/contact', permanent: true },
  { source: '/properties-madurai-builders', destination: '/projects/ongoing', permanent: true },
  { source: '/about-visvas-promoters', destination: '/about', permanent: true },
  { source: '/madhyapuri-2-bhk-3-bhk-apartments-ellis-nagar', destination: '/projects/madhyapuri', permanent: true },
  { source: '/testimonials', destination: '/', permanent: true },
  { source: '/inquiry-form', destination: '/contact', permanent: true },
  { source: '/insights', destination: '/blog', permanent: true },
  { source: '/faq-visvas-promoters-1-best-builder-in-madurai', destination: '/', permanent: true },
  { source: '/services', destination: '/', permanent: true },
  { source: '/privacy', destination: '/', permanent: true },
  { source: '/terms-and-conditions', destination: '/', permanent: true },

  // Houzez portal/account pages
  { source: '/my-profile', destination: '/', permanent: true },
  { source: '/rent', destination: '/', permanent: true },
  { source: '/buy', destination: '/', permanent: true },
  { source: '/complete-order', destination: '/', permanent: true },
  { source: '/packages', destination: '/', permanent: true },
  { source: '/search-results', destination: '/', permanent: true },
  { source: '/create-listing', destination: '/', permanent: true },
  { source: '/board', destination: '/', permanent: true },
  { source: '/saved-search', destination: '/', permanent: true },
  { source: '/membership-info', destination: '/', permanent: true },
  { source: '/invoices', destination: '/', permanent: true },
  { source: '/thank-you', destination: '/', permanent: true },
  { source: '/stripe', destination: '/', permanent: true },
  { source: '/compare-properties', destination: '/', permanent: true },
  { source: '/favorite-properties', destination: '/', permanent: true },
  { source: '/my-properties', destination: '/', permanent: true },
]
